apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfohelm
  namespace: default
spec:
  chart:
    spec:
      chart: podinfo
      version: '5.0.x'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfohelm
  interval: 1m0s
  releaseName: podinfohelm
